export interface VideoModel {
  id: string // Replicate model path (e.g., 'google/veo-3.1')
  name: string // Display name
  description?: string
  supportsTextToVideo: boolean
  supportsImageToVideo: boolean
  supportsCharacterReference: boolean
  supportsFirstFrame: boolean
  supportsCustomDuration: boolean
  defaultDuration?: number
  durationOptions?: number[] // Valid duration values
  aspectRatioOptions: ('16:9' | '9:16' | '1:1')[]
  requiredInputs: string[] // e.g., ['prompt', 'image']
  optionalInputs: string[] // e.g., ['first_frame_image', 'subject_reference']
}

/**
 * Story represents a narrative structure for the video.
 * Generated by OpenAI MCP's generate_stories tool.
 * Users choose from 3 story options before storyboard generation.
 */
export interface Story {
  /** Unique identifier for the story option (1, 2, or 3) */
  id: number
  /** Short title summarizing the story approach */
  title: string
  /** 2-3 sentence narrative describing the story flow */
  narrative: string
  /** Emotional arc: e.g., "curiosity → surprise → satisfaction" */
  emotionalArc: string
  /** Brief list of key story beats (3-5 items) */
  keyBeats: string[]
  /** Target audience this story resonates with most */
  targetAudience: string
  /** Why this story works (1-2 sentences) */
  rationale: string
}

/**
 * Segment represents a single section of the video storyboard.
 * Each segment has visual and audio components, plus keyframe images.
 */
export interface Segment {
  type: 'hook' | 'body' | 'cta'
  description: string
  startTime: number
  endTime: number
  visualPrompt: string
  visualPromptAlternatives?: string[] // Array of alternative visual prompts for user selection
  selectedPromptIndex?: number // Index of selected prompt (0 = visualPrompt, 1+ = alternatives)
  audioNotes?: string
  
  // Legacy fields (will be deprecated in favor of keyframe URLs)
  firstFrameImage?: string // File path or URL for first frame image
  subjectReference?: string // File path or URL for subject reference image
  
  // NEW: Keyframe URLs generated by GPT-4o-mini → Seedream pipeline
  /** URL of the generated first frame keyframe (from keyframe-generator) */
  firstFrameUrl?: string
  /** URL of the generated last frame keyframe (from keyframe-generator) */
  lastFrameUrl?: string
  /** Enhanced composition prompt used for keyframe generation */
  enhancedPrompt?: string
  /** Timestamp when keyframes were generated */
  keyframesGeneratedAt?: number
  /** Status of keyframe generation */
  keyframeStatus?: 'pending' | 'generating' | 'completed' | 'failed'
  /** Error message if keyframe generation failed */
  keyframeError?: string
  
  status?: 'pending' | 'processing' | 'completed' | 'failed'
}

/**
 * Storyboard represents the complete video plan with segments and metadata.
 * Generated from a user's prompt, selected story, and product images.
 */
export interface Storyboard {
  id: string
  segments: Segment[]
  meta: {
    duration: number
    aspectRatio: '16:9' | '9:16' | '1:1'
    style: string
    mode?: 'demo' | 'production'
    model?: string // Video model ID (e.g., 'google/veo-3.1')
    
    // Legacy fields
    firstFrameImage?: string // Global default first frame image path/URL
    subjectReference?: string // Global default subject reference image path/URL
    
    // NEW: Story and product information
    /** Selected story narrative that guides the storyboard */
    story?: Story
    /** User's original text prompt */
    originalPrompt?: string
    /** URLs of product reference images (1-10 images) */
    productImages?: string[]
    /** Product name extracted from prompt */
    productName?: string
    /** Additional brand information */
    brandInfo?: {
      colors?: string[] // Brand colors (hex codes)
      logoUrl?: string // Brand logo URL
      tagline?: string // Brand tagline
    }
  }
  createdAt: number
  updatedAt?: number
}

export interface Asset {
  segmentId: number
  videoUrl?: string
  voiceUrl?: string
  status: 'pending' | 'processing' | 'completed' | 'failed'
  error?: string
  metadata?: {
    predictionId?: string
    replicateVideoUrl?: string
    voiceUrl?: string
    segmentIndex?: number
    segmentType?: string
    startTime?: number
    endTime?: number
    duration?: number
    timestamp?: number
    [key: string]: any // Allow additional metadata fields
  }
}

export interface GenerationJob {
  id: string
  status: 'processing' | 'completed' | 'failed'
  startTime: number
  endTime?: number
  assets?: Asset[]
  error?: string
  storyboardId: string
}

export interface ParsedPrompt {
  product: string
  targetAudience: string
  mood: string
  keyMessages: string[]
  visualStyle: string
  callToAction: string
  meta: {
    duration: number
    aspectRatio: '16:9' | '9:16' | '1:1'
    style: string
    mode?: 'demo' | 'production'
    model?: string // Video model ID
    firstFrameImage?: string
    subjectReference?: string
  }
}

export interface Video {
  id: string
  url: string
  duration: number
  resolution: string
  aspectRatio: '16:9' | '9:16' | '1:1'
  generationCost: number
  createdAt: number
  storyboardId: string
  jobId: string
}

export interface CostEntry {
  operation: string
  amount: number
  timestamp: number
  metadata?: Record<string, any>
}

export interface CostSummary {
  total: number
  byOperation: Record<string, number>
  count: number
}

